### ISSUE TITLE
数据集能提供一下吗？BSCD

### ISSUE THREAD

**Issue by yyds-xtt** [Tnnidm/ServicePlacement#1]
数据集能提供一下吗？BSCD

**Comment by yyds-xtt** [comment]
数据集能提供一下吗？BSCD

**Comment by yyds-xtt** [comment]
数据集能提供一下吗？BSCD

**Comment by yyds-xtt** [comment]
数据集能提供一下吗？BSCD

**Comment by yyds-xtt** [comment]
数据集能提供一下吗？BSCD

**Comment by yyds-xtt** [comment]
数据集能提供一下吗？BSCD

**Comment by yyds-xtt** [comment]
数据集能提供一下吗？BSCD

**Comment by yyds-xtt** [comment]
数据集能提供一下吗？BSCD

**Comment by yyds-xtt** [comment]
数据集能提供一下吗？BSCD

**Comment by yyds-xtt** [comment]
BSCD
contains the locations of 46050 BSes run by CMCC and
CUCC in Chendu City collected in Dec. 2019, among which
1910 BSes in the northeast of the city (30.653°N - 30.705°N
and 104.042°E - 104.122°E) are utilized in the performance
evaluation. 2) DECD18 includes the trajectories of Didi
expresses in Chendu City during Oct 8, 2018 - Oct 31, 2018.
The location of each express is updated every 20 seconds.

数据集  BSCD  DECD18 能提供一下吗

**Comment by yyds-xtt** [comment]
BSCD
contains the locations of 46050 BSes run by CMCC and
CUCC in Chendu City collected in Dec. 2019, among which
1910 BSes in the northeast of the city (30.653°N - 30.705°N
and 104.042°E - 104.122°E) are utilized in the performance
evaluation. 2) DECD18 includes the trajectories of Didi
expresses in Chendu City during Oct 8, 2018 - Oct 31, 2018.
The location of each express is updated every 20 seconds.

数据集 BSCD DECD18 能提供一下吗

**Comment by Tnnidm** [comment]
已邮件回复
