### ISSUE TITLE
大佬

### ISSUE THREAD

**Issue by yyds-xtt** [Tnnidm/ServicePlacement#2]
'chengdushi_1010_1020.csv',   这个文件的数据格式能说一下吗，大佬，您的数据处理的看不懂。或者给个chengdushi_1010_1020.csv文件

**Comment by Tnnidm** [comment]
抱歉，作为一个学生，我没权限开放当时以实验室名义申请的数据集，而且滴滴的条款也要求不能传播这个数据集。实际上你用任何一个城市的车辆轨迹数据集讲道理都可以复现结果，并不一定要纠结于成都的数据集。'chengdushi_1010_1020.csv'文件有很多列，但是实际上用到的只有时间戳和位置信息，其他的我有点忘了，因为是本科时候写的代码了

**Comment by Tnnidm** [comment]
我回忆了一下preprocess_car最后保存的dict_Car_'+str(i-1)+'.txt'是一个字典的字典，键是第几天，值是一个包含当天很多车轨迹arr的字典。preprocess_car_2就是用来生成每个时刻系统要进入哪些车的索引。希望对你有帮助。

**Comment by Tnnidm** [comment]
我回忆了一下preprocess_car最后保存的dict_Car_'+str(i-1)+'.txt'是一个字典，i是第几天，键是车的index，值是车轨迹arr。preprocess_car_2就是用来生成每个时刻系统要进入哪些车的索引。希望对你有帮助。

**Comment by yyds-xtt** [comment]
我不是要你们的数据集，给几组样例可以吗？
这是我找的成都的数据集，这是其中一天的。但是和你的 chengdushi_1010_1020.csv 不一样，你这个应该是10~20天放在一起的。所以，我只是想要几组测试样例，把我的数据处理成和chengdushi_1010_1020.csv一样。

1,30.566131,103.958195,0,2014/8/16 08:46:23
1,30.566141,103.957807,0,2014/8/16 08:46:14
1,30.566299,103.958325,0,2014/8/16 08:46:27
1,30.566885,103.955569,0,2014/8/16 08:45:43
1,30.567404,103.955252,0,2014/8/16 08:45:38
1,30.568289,103.955642,0,2014/8/16 08:45:31
1,30.569262,103.959754,0,2014/8/16 08:46:57
1,30.570154,103.971837,0,2014/8/16 08:48:29
1,30.570406,103.970178,1,2014/8/16 08:42:15
1,30.570486,103.956594,0,2014/8/16 08:45:00
1,30.570670,103.975451,0,2014/8/16 08:49:00
1,30.570716,103.973742,1,2014/8/16 08:41:54
1,30.570923,103.966819,0,2014/8/16 08:47:59
1,30.571083,103.975437,1,2014/8/16 08:41:24
1,30.571083,103.975571,1,2014/8/16 08:40:53
1,30.571270,103.957002,1,2014/8/16 08:43:58
1,30.571373,103.977502,1,2014/8/16 08:40:22
1,30.571374,103.957097,0,2014/8/16 08:44:29
1,30.571586,103.979347,0,2014/8/16 08:49:31
1,30.571729,103.964786,1,2014/8/16 08:42:46
1,30.572497,103.961823,0,2014/8/16 08:47:28
1,30.572504,103.984156,1,2014/8/16 08:39:52
1,30.572582,103.985079,0,2014/8/16 08:50:01
1,30.573420,103.958244,1,2014/8/16 08:43:28
1,30.573422,103.959929,1,2014/8/16 08:43:16
1,30.573758,103.991734,0,2014/8/16 08:50:32
1,30.573998,103.992518,1,2014/8/16 08:39:21

**Comment by Tnnidm** [comment]
嗯嗯理解。刚刚我复制用read_csv读取一行并打印出来如下，你可以参考一下：
[['c15360a08d5c29bdc08faccaa4f948bb', 'cf5f05319d9d75e74bf25a23787270be', '[104.12897 30.70673 1540081088, 104.12836 30.70653 1540081091, 104.12772 30.70635 1540081094, 104.12708 30.70616 1540081097, 104.12644 30.70596 1540081100, 104.1258 30.70574 1540081103, 104.12536 30.70561 1540081106, 104.12471 30.70541 1540081110, 104.12405 30.70521 1540081112, 104.12342 30.70502 1540081115, 104.1228 30.70483 1540081118, 104.12219 30.70465 1540081121, 104.12158 30.70446 1540081124, 104.12097 30.70429 1540081127, 104.12034 30.70416 1540081130, 104.11972 30.70406 1540081133, 104.11907 30.70398 1540081136, 104.1184 30.70395 1540081139, 104.11772 30.70396 1540081142, 104.11703 30.70397 1540081145, 104.11635 30.70397 1540081148, 104.11568 30.70397 1540081151, 104.115 30.70397 1540081154, 104.11431 30.70396 1540081157, 104.11361 30.70396 1540081160, 104.11292 30.70395 1540081163, 104.11223 30.70395 1540081166, 104.11154 30.70395 1540081169, 104.11086 30.70395 1540081172, 104.11017 30.70395 1540081175, 104.10947 30.70395 1540081178, 104.10876 30.70395 1540081181, 104.10806 30.70395 1540081184, 104.10736 30.70395 1540081187, 104.10668 30.70395 1540081190, 104.10602 30.70394 1540081193, 104.10539 30.70394 1540081196, 104.10484 30.70394 1540081199, 104.10437 30.70388 1540081202, 104.10403 30.70377 1540081205, 104.10376 30.7036 1540081208, 104.10351 30.70336 1540081211, 104.10327 30.70305 1540081214, 104.10314 30.70268 1540081217, 104.10311 30.70226 1540081220, 104.10329 30.70177 1540081223, 104.10351 30.70142 1540081226, 104.10374 30.70104 1540081229, 104.104 30.70062 1540081232, 104.10426 30.7002 1540081235, 104.10449 30.69985 1540081238, 104.10469 30.69952 1540081241, 104.10489 30.6992 1540081244, 104.1051 30.69889 1540081247, 104.10532 30.69856 1540081250, 104.10554 30.69822 1540081253, 104.10577 30.69788 1540081256, 104.10598 30.69752 1540081259, 104.1062 30.6972 1540081262, 104.10639 30.69688 1540081265, 104.10652 30.69667 1540081268, 104.10672 30.69632 1540081271, 104.10696 30.69595 1540081274, 104.1072 30.69558 1540081277, 104.10745 30.6952 1540081280, 104.10768 30.69485 1540081283, 104.10788 30.69452 1540081286, 104.10801 30.69417 1540081289, 104.10805 30.6938 1540081292, 104.10802 30.69345 1540081295, 104.10786 30.69309 1540081298, 104.10764 30.69274 1540081301, 104.10733 30.69239 1540081304, 104.10702 30.69201 1540081307, 104.10671 30.69162 1540081310, 104.10639 30.69121 1540081313, 104.10609 30.69083 1540081316, 104.10583 30.6905 1540081319, 104.10556 30.69017 1540081322, 104.10529 30.68983 1540081325, 104.105 30.68947 1540081328, 104.10471 30.68911 1540081331, 104.10442 30.68873 1540081334, 104.10412 30.68836 1540081337, 104.10382 30.688 1540081340, 104.10365 30.68778 1540081343, 104.10342 30.68747 1540081346, 104.10329 30.68729 1540081349, 104.10315 30.68711 1540081352, 104.103 30.68692 1540081355, 104.10284 30.68671 1540081358, 104.10266 30.68648 1540081361, 104.10247 30.68623 1540081364, 104.10227 30.68597 1540081367, 104.10207 30.68573 1540081370, 104.10188 30.6855 1540081373, 104.10169 30.68527 1540081376, 104.10153 30.68505 1540081379, 104.10137 30.68483 1540081382, 104.10121 30.68461 1540081385, 104.10106 30.68439 1540081388, 104.10091 30.6842 1540081391, 104.10076 30.68401 1540081394, 104.10063 30.68385 1540081397, 104.1005 30.68373 1540081400, 104.10047 30.68367 1540081403, 104.10047 30.68367 1540081406, 104.10047 30.68367 1540081409, 104.10048 30.68367 1540081412, 104.10048 30.68367 1540081415, 104.10044 30.6836 1540081418, 104.10033 30.68345 1540081421, 104.10019 30.68328 1540081424, 104.10003 30.68311 1540081427, 104.09991 30.68297 1540081430, 104.0998 30.68283 1540081433, 104.09966 30.68266 1540081436, 104.0995 30.68249 1540081439, 104.09936 30.68233 1540081442, 104.09923 30.68217 1540081445, 104.09909 30.68201 1540081448, 104.09894 30.68182 1540081451, 104.09875 30.68162 1540081454, 104.09856 30.68138 1540081457, 104.09837 30.68112 1540081460, 104.09817 30.68086 1540081463, 104.09795 30.68062 1540081466, 104.09774 30.68039 1540081469, 104.09756 30.68017 1540081472, 104.09747 30.68005 1540081475, 104.09728 30.67983 1540081478, 104.09723 30.67979 1540081481, 104.0972 30.67981 1540081484, 104.0972 30.67981 1540081487, 104.0972 30.67981 1540081490, 104.0972 30.67981 1540081493, 104.09709 30.67982 1540081496, 104.09707 30.67981 1540081499, 104.09707 30.67981 1540081502, 104.09707 30.67981 1540081505, 104.09707 30.67981 1540081508, 104.09707 30.67981 1540081511, 104.09707 30.67981 1540081514, 104.09707 30.67981 1540081517, 104.09707 30.6798 1540081520, 104.09705 30.67974 1540081523, 104.09701 30.6796 1540081526, 104.09695 30.67944 1540081529, 104.09684 30.67925 1540081532, 104.09662 30.67904 1540081535, 104.09637 30.67875 1540081538, 104.09613 30.67847 1540081541, 104.09589 30.67819 1540081544, 104.09567 30.67786 1540081547, 104.0955 30.67755 1540081550, 104.0953 30.67729 1540081553, 104.09511 30.67708 1540081556, 104.09488 30.67702 1540081559, 104.09463 30.67694 1540081562, 104.09451 30.67677 1540081565, 104.09452 30.67654 1540081568, 104.09459 30.67633 1540081571, 104.09466 30.67626 1540081574, 104.09471 30.6763 1540081577, 104.09486 30.67627 1540081580, 104.09508 30.67625 1540081583, 104.09536 30.67616 1540081586, 104.09562 30.67603 1540081589, 104.09591 30.67581 1540081592, 104.09634 30.67543 1540081595, 104.09664 30.67515 1540081598, 104.09693 30.67488 1540081601, 104.09721 30.67457 1540081604, 104.09744 30.67425 1540081607, 104.09761 30.67394 1540081610, 104.09776 30.67359 1540081613, 104.0979 30.6732 1540081616, 104.09803 30.67285 1540081619, 104.09813 30.67256 1540081622, 104.09821 30.67239 1540081625, 104.09817 30.67225 1540081628, 104.09805 30.67218 1540081631, 104.09782 30.6721 1540081634, 104.09756 30.67201 1540081637, 104.09735 30.67197 1540081640, 104.09715 30.67192 1540081643, 104.09702 30.6719 1540081646, 104.09701 30.67188 1540081649, 104.09701 30.67188 1540081652, 104.09701 30.67188 1540081654]']]

**Comment by yyds-xtt** [comment]
大佬，你这个chengdushi_1010_1020.csv文件，行，列代表啥意思。能麻烦解释一下吗

**Comment by Tnnidm** [comment]
它这个文件写的很脏，所以当时预处理这个文件觉得非常恶心，所以还是希望你们不要重蹈覆辙了。。。我的理解是每行代表一辆车的一条轨迹，前两列都是这辆车的身份哈希值，第三列是转化成string的一个轨迹数组。这个数组里面每行代表一个时间节点，前两列是经度，第三列是时间戳。

**Comment by yyds-xtt** [comment]
chengdushi_1010_1020.csv 这个 ‘轨迹数组’，是多久的，1天的吗，还是？

**Comment by Tnnidm** [comment]
不1010_1020表示的是10月10日到20日。

**Comment by yyds-xtt** [comment]
好的，谢谢

**Comment by Tnnidm** [comment]
哦对了，如果你问的是“第三列是转化成string的一个轨迹数组”这句话里面的“轨迹数组”的长度，它不是10天的，它是随便多长的，取决于滴滴网约车某个订单的轨迹有多长。chengdushi_1010_1020.csv的意思是包含了10月10号到20号的这些网约车订单的轨迹数组。

**Comment by yyds-xtt** [comment]
好的， 谢谢。1540081298 这个时间戳怎么 计算的？

**Comment by Tnnidm** [comment]
这些时间戳是他那个数据集自带的，估计是他们unix机器自己的时间戳吧。至于代码里面min_time = 1538336145.0这里哈哈哈实际上是观察出来的，估计了一下那个时间戳大概是0点（不一定准确）
